//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Razrabotka.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string ACodeword { get; set; }
        public string SecretQuestionAnswer { get; set; }
        public int CodeSecretQuestion1 { get; set; }
        public int CodeUser { get; set; }
    
        public virtual SecretQuestion SecretQuestion { get; set; }
    }
}
